import type { Metadata } from "next";
import "./globals.css";
import NavigationMenu from "@/components/Layout/NavigationMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={`h-[calc(100dvh)] p-[30px]`}>
          <div className="flex">
            <div className="">
              <div className="flex gap-[5px]">
                <NavigationMenu></NavigationMenu>
                <div className="w-[calc(100vw-310px)] h-[calc(100vh-60px)]">
                  {children}
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
